### PR TITLE
IOLink Removed spaces for text field DI_C/Q (Pin4)

### PR DESCRIPTION
**Pull request by JesperHakansson**

### CODE REVIEW

**Comment by opcfoundation-org** [comment]
What is the mantis issue for this fix.
See https://mantis.opcfoundation.org/set_project.php?project_id=124&amp;make_default=no

**Comment by JesperHakansson** [comment]
Hi,

I found the extra spaces in the IOLink nodeset file when I was verifying all OPC UA companion specifications with our product.
I don’t have an account on the bug tracker so I haven’t seen if anyone else has reported this.
Must there be an issue report in Mantis before an issue is solved?

Best regards
Jesper

**Comment by opcfoundation-org** [comment]
Each NodeSet in the repo is managed by a different group and the majority of them do not monitor this site. 
If you log an issue in Mantis then the right people will get a email telling them that a problem exists.

**Comment by JesperHakansson** [comment]
https://mantis.opcfoundation.org/view.php?id=7434

**Pull request closed without merging**
